"""Add video_url and completed_chapters

Revision ID: 096a64f082fc
Revises: 9e91c28a06e1
Create Date: 2026-04-08 00:56:46.419705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096a64f082fc'
down_revision: Union[str, None] = '9e91c28a06e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(), nullable=True))

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_chapters', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('completed_chapters')

    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
