"""Add Google Integration Links

Revision ID: 9e91c28a06e1
Revises: af25d1cf922e
Create Date: 2026-04-08 00:21:10.093509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e91c28a06e1'
down_revision: Union[str, None] = 'af25d1cf922e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materials_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('google_classroom_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('google_meet_link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('google_meet_link')
        batch_op.drop_column('google_classroom_link')
        batch_op.drop_column('materials_link')

    # ### end Alembic commands ###
